### PR TITLE
Fix undefined variable causing undefined behaviour

### LINKED ISSUE #2719: [2.7.0RC1] Undefined variable
My debugger throws up because of [this new delegate][1]. It says `$c`is undefined, and I’m not exactly sure what `$c`should be or where it comes from.

[1]: https://github.com/symphonycms/symphony-2/blob/2.7.x/symphony/lib/toolkit/class.administrationpage.php#L1072

### PR DESCRIPTION
**Pull request by nitriques**
$c was not declared in that context.
85f30f3e4caaf2983c770e08b28011e9bdc82319 must have introduced a typical
copy/paste error.

Sections are given the default 'author' limit.

Fixes #2719

### CODE REVIEW

File: symphony/lib/toolkit/class.administrationpage.php [hunk 1]
```diff
@@ -1066,11 +1072,15 @@ private function buildSectionNavigation(&$nav)
...
+                 * @param int $section.id
+                 *  The id of the section for this url
+                 * @param string $section.handle
+                 *  The handle of the section for this url
                  */
                 Symphony::ExtensionManager()->notifyMembers('CanAccessPage', '/backend/', array(
                     'allowed' => &$hasAccess,
-                    'page_limit' => $c['limit'],
-                    'page_url' => $c['link'],
+                    'page_limit' => 'author',
```
Comment (brendo) [inline symphony/lib/toolkit/class.administrationpage.php]: Could this be `$page_limit` instead?

Comment (nitriques) [inline symphony/lib/toolkit/class.administrationpage.php]: Sections do not have page limits, do they ?

Comment (nitriques) [inline symphony/lib/toolkit/class.administrationpage.php]: I think you got mixed up (like I was) because of the way the diff is displayed. There are a lot of code in between ;)

**Comment by nitriques** [comment]
@michael-e @jensscherbl guys, **if you have the time**, can you approve this PR ? Or tell me you can't review it :+1:

**Comment by nitriques** [comment]
No problem @michael-e ;)

File: symphony/lib/toolkit/class.administrationpage.php (hunk 1 above)
Comment (brendo) [inline symphony/lib/toolkit/class.administrationpage.php]: Yeah sorry, diff view got me too :)
