### PR TITLE
Make Configuration::__toString() support nested arrays

### LINKED ISSUE #2519: Make Configuration::__toString support arrays as values
Right now, doing `Symphony::Configuration()->set('key', array(), 'group');` makes any write calls crash.

It would be nice (and easy) to support it.
- [x] Make Configuration::__toString support arrays as values
- [x] Serialize indentation with spaces instead

### PR DESCRIPTION
**Pull request by ChoboHub**
Fixes #2519

### CODE REVIEW

File: symphony/lib/core/class.configuration.php [hunk 1]
```diff
@@ -175,17 +175,18 @@ public function flush()
...
         $string = 'array(';
+        $tab = "\t";
 
         foreach ($this->_properties as $group => $data) {
-            $string .= str_repeat(PHP_EOL, 3) . "\t\t###### ".strtoupper($group)." ######";
-            $string .= PHP_EOL . "\t\t'$group' => ";
+            $string .= str_repeat(PHP_EOL, 3) . "$tab$tab###### ".strtoupper($group)." ######";
+            $string .= PHP_EOL . "$tab$tab'$group' => ";
 
             $string .= $this->serializeArray($data, 3);
```
Comment (nitriques) [inline symphony/lib/core/class.configuration.php]: We need to pass the $tab parameter here

**Comment by ChoboHub** [comment]
here it is

File: symphony/lib/core/class.configuration.php [hunk 2]
```diff
@@ -28,6 +28,12 @@ class Configuration
     private $_forceLowerCase = false;
 
     /**
+     * The string representing the tab character used to serialize the configuration
+     * @var string
```
Comment (nitriques) [inline symphony/lib/core/class.configuration.php]: character -> character(s)

Sorry!

**Comment by nitriques** [comment]
All right!

LGTM!

@brendo @michael-e would you mind a quick review please ? Thanks guys.

File: symphony/lib/core/class.configuration.php (hunk 2 above)
Comment (michael-e) [inline symphony/lib/core/class.configuration.php]: Plural? Are you sure?

Comment (nitriques) [inline symphony/lib/core/class.configuration.php]: Well, it's 4 spaces...

File: symphony/lib/core/class.configuration.php [hunk 3]
```diff
@@ -28,6 +28,12 @@ class Configuration
     private $_forceLowerCase = false;
 
     /**
+     * The string representing the tab characters used to serialize the configuration
+     * @var string
+     */
+    const TAB = '    ';
```
Comment (brendo) [inline symphony/lib/core/class.configuration.php]: `\t` has better cross platform support (although really we should probably move to space)

**Comment by brendo** [comment]
No problems, just note that all of it can essentially replaced if we want to.... https://github.com/brendo/symphony-2/blob/cfccb23f4d91db862dbdc7389768a2ccdf7a9602/symphony/lib/core/class.configuration.php#L173-L180

File: symphony/lib/core/class.configuration.php (hunk 3 above)
Comment (nitriques) [inline symphony/lib/core/class.configuration.php]: Yeah, I've changed it to spaces since all of our generated files and our code files are indented with 4 spaces

**Comment by nitriques** [comment]
I've thought of that (using only var_dumps) but we got rid of the nice comments we provide.. and I like them haha
